# Generated by Django 5.2.5 on 2025-08-11 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_created_at_habit_last_reminded_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-created_at', 'id'], 'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.AlterField(
            model_name='habit',
            name='execution_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Время на выполнение (в секундах)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность (в днях)'),
        ),
    ]
