# Generated by Django 5.2.5 on 2025-08-10 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramaccount',
            options={'verbose_name': 'Аккаунт Telegram', 'verbose_name_plural': 'Аккаунты Telegram'},
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='chat_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='Chat ID'),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
